export const solarBodies = [
  {
    id: 'mercury',
    name: '水星',
    englishName: 'Mercury',
    type: '岩石行星',
    orbit: 84,
    size: 11,
    orbitDuration: 8,
    rotationDuration: 5,
    orbitTilt: 6,
    orbitYaw: -10,
    colorClass: 'mercury',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/pia15162-mercury-basins-messenger-16x9-1.jpg?w=1024',
    imageAlt: 'NASA MESSENGER spacecraft image of Mercury.',
    imageCredit: 'NASA / Johns Hopkins APL / Carnegie Institution of Washington',
    order: '第 1 顆行星',
    distance: '平均距離太陽約 5,790 萬公里',
    diameter: '直徑約 4,879 公里',
    mass: '質量約為地球的 0.055 倍',
    composition: '岩石、金屬核心，幾乎沒有大氣',
    rotation: '自轉約 58.6 個地球日',
    revolution: '公轉約 88 個地球日',
    temperature: '白天很熱、夜晚很冷，溫差極大',
    moons: '0 顆衛星',
    kidFact: '水星最靠近太陽，但因為幾乎沒有大氣保溫，夜晚會變得非常寒冷。',
    en: {
      name: 'Mercury',
      type: 'Rocky planet',
      order: '1st planet from the Sun',
      distance: 'Average distance from the Sun: about 57.9 million km',
      diameter: 'Diameter: about 4,879 km',
      mass: "Mass: about 0.055 times Earth's mass",
      composition: 'Rocky body with a metallic core and almost no atmosphere',
      rotation: 'Rotation: about 58.6 Earth days',
      revolution: 'Orbit: about 88 Earth days',
      temperature: 'Very hot by day and very cold at night, with extreme temperature swings',
      moons: '0 moons',
      kidFact:
        'Mercury is closest to the Sun, but because it has almost no atmosphere to hold heat, its nights become very cold.',
    },
  },
  {
    id: 'venus',
    name: '金星',
    englishName: 'Venus',
    type: '岩石行星',
    orbit: 116,
    size: 17,
    orbitDuration: 12,
    rotationDuration: 10,
    orbitTilt: 3,
    orbitYaw: 14,
    colorClass: 'venus',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/venus-mariner-10-pia23791-fig2-16x9-1.jpg?w=1024',
    imageAlt: 'NASA Mariner 10 image of Venus.',
    imageCredit: 'NASA / JPL-Caltech',
    order: '第 2 顆行星',
    distance: '平均距離太陽約 1.082 億公里',
    diameter: '直徑約 12,104 公里',
    mass: '質量約為地球的 0.815 倍',
    composition: '岩石星球，厚重大氣主要是二氧化碳',
    rotation: '自轉約 243 個地球日，方向和多數行星相反',
    revolution: '公轉約 225 個地球日',
    temperature: '表面溫度約 465°C，是最熱的行星',
    moons: '0 顆衛星',
    kidFact: '金星有很厚的雲和溫室效應，所以比離太陽更近的水星還熱。',
    en: {
      name: 'Venus',
      type: 'Rocky planet',
      order: '2nd planet from the Sun',
      distance: 'Average distance from the Sun: about 108.2 million km',
      diameter: 'Diameter: about 12,104 km',
      mass: "Mass: about 0.815 times Earth's mass",
      composition: 'Rocky planet with a thick atmosphere made mostly of carbon dioxide',
      rotation: 'Rotation: about 243 Earth days, opposite the direction of most planets',
      revolution: 'Orbit: about 225 Earth days',
      temperature: 'Surface temperature: about 465°C, making it the hottest planet',
      moons: '0 moons',
      kidFact:
        'Venus has thick clouds and a strong greenhouse effect, so it is hotter than Mercury even though Mercury is closer to the Sun.',
    },
  },
  {
    id: 'earth',
    name: '地球',
    englishName: 'Earth',
    type: '岩石行星',
    orbit: 150,
    size: 18,
    orbitDuration: 16,
    rotationDuration: 2.5,
    orbitTilt: 0,
    orbitYaw: 0,
    colorClass: 'earth',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/blue-marble-apollo-17-16x9-1.jpg?w=1024',
    imageAlt: 'Apollo 17 Blue Marble image of Earth.',
    imageCredit: 'NASA',
    order: '第 3 顆行星',
    distance: '平均距離太陽約 1.496 億公里',
    diameter: '直徑約 12,756 公里',
    mass: '質量約 5.97 x 10^24 公斤',
    composition: '岩石、金屬核心、水、氮氣與氧氣大氣',
    rotation: '自轉約 24 小時',
    revolution: '公轉約 365.25 天',
    temperature: '平均表面溫度約 15°C',
    moons: '1 顆衛星：月球',
    kidFact: '地球目前是我們知道唯一有大量液態水和生命的行星。',
    en: {
      name: 'Earth',
      type: 'Rocky planet',
      order: '3rd planet from the Sun',
      distance: 'Average distance from the Sun: about 149.6 million km',
      diameter: 'Diameter: about 12,756 km',
      mass: 'Mass: about 5.97 x 10^24 kg',
      composition: 'Rock, metallic core, water, and an atmosphere of nitrogen and oxygen',
      rotation: 'Rotation: about 24 hours',
      revolution: 'Orbit: about 365.25 days',
      temperature: 'Average surface temperature: about 15°C',
      moons: '1 moon: the Moon',
      kidFact:
        'Earth is currently the only planet we know with abundant liquid water and life.',
    },
  },
  {
    id: 'mars',
    name: '火星',
    englishName: 'Mars',
    type: '岩石行星',
    orbit: 186,
    size: 14,
    orbitDuration: 22,
    rotationDuration: 2.7,
    orbitTilt: 4,
    orbitYaw: -24,
    colorClass: 'mars',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/mars-full-globe-16x9-1.jpg?w=1024',
    imageAlt: 'NASA spacecraft image of Mars as a full globe.',
    imageCredit: 'NASA / JPL-Caltech',
    order: '第 4 顆行星',
    distance: '平均距離太陽約 2.279 億公里',
    diameter: '直徑約 6,792 公里',
    mass: '質量約為地球的 0.107 倍',
    composition: '岩石、鐵氧化物塵土、稀薄二氧化碳大氣',
    rotation: '自轉約 24.6 小時',
    revolution: '公轉約 687 個地球日',
    temperature: '平均約 -65°C',
    moons: '2 顆衛星：火衛一、火衛二',
    kidFact: '火星看起來偏紅，是因為表面有像鐵鏽一樣的物質。',
    en: {
      name: 'Mars',
      type: 'Rocky planet',
      order: '4th planet from the Sun',
      distance: 'Average distance from the Sun: about 227.9 million km',
      diameter: 'Diameter: about 6,792 km',
      mass: "Mass: about 0.107 times Earth's mass",
      composition: 'Rock, iron-oxide dust, and a thin carbon dioxide atmosphere',
      rotation: 'Rotation: about 24.6 hours',
      revolution: 'Orbit: about 687 Earth days',
      temperature: 'Average temperature: about -65°C',
      moons: '2 moons: Phobos and Deimos',
      kidFact: 'Mars looks reddish because its surface contains rusty iron-rich material.',
    },
  },
  {
    id: 'jupiter',
    name: '木星',
    englishName: 'Jupiter',
    type: '氣體巨行星',
    orbit: 234,
    size: 38,
    orbitDuration: 36,
    rotationDuration: 1.6,
    orbitTilt: 1,
    orbitYaw: 8,
    colorClass: 'jupiter',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/jupiter-marble-pia22946-16x9-1.jpg?w=1024',
    imageAlt: 'NASA Juno image of Jupiter.',
    imageCredit: 'NASA / JPL-Caltech / SwRI / MSSS',
    order: '第 5 顆行星',
    distance: '平均距離太陽約 7.785 億公里',
    diameter: '直徑約 142,984 公里',
    mass: '質量約為地球的 317.8 倍',
    composition: '主要由氫和氦組成',
    rotation: '自轉約 9.9 小時',
    revolution: '公轉約 11.86 個地球年',
    temperature: '雲頂平均約 -110°C',
    moons: '已知有許多衛星，包含伽利略四大衛星',
    kidFact: '木星是太陽系最大的行星，上面的「大紅斑」是一個持續很久的大風暴。',
    en: {
      name: 'Jupiter',
      type: 'Gas giant',
      order: '5th planet from the Sun',
      distance: 'Average distance from the Sun: about 778.5 million km',
      diameter: 'Diameter: about 142,984 km',
      mass: "Mass: about 317.8 times Earth's mass",
      composition: 'Made mostly of hydrogen and helium',
      rotation: 'Rotation: about 9.9 hours',
      revolution: 'Orbit: about 11.86 Earth years',
      temperature: 'Average cloud-top temperature: about -110°C',
      moons: 'Many known moons, including the four large Galilean moons',
      kidFact:
        'Jupiter is the largest planet in the solar system, and its Great Red Spot is a giant storm that has lasted a very long time.',
    },
  },
  {
    id: 'saturn',
    name: '土星',
    englishName: 'Saturn',
    type: '氣體巨行星',
    orbit: 288,
    size: 34,
    orbitDuration: 46,
    rotationDuration: 1.8,
    orbitTilt: 2,
    orbitYaw: -18,
    colorClass: 'saturn',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2023/05/pia05380-saturn-with-rings-16x9-1.jpg',
    imageAlt: 'NASA Cassini image of Saturn with its ring system centered in frame.',
    imageCredit: 'NASA / JPL / Space Science Institute',
    hasRing: true,
    order: '第 6 顆行星',
    distance: '平均距離太陽約 14.34 億公里',
    diameter: '直徑約 120,536 公里',
    mass: '質量約為地球的 95.2 倍',
    composition: '主要由氫和氦組成，擁有明顯冰與岩石碎片環',
    rotation: '自轉約 10.7 小時',
    revolution: '公轉約 29.45 個地球年',
    temperature: '雲頂平均約 -140°C',
    moons: '已知有許多衛星，土衛六是其中很重要的一顆',
    kidFact: '土星最有名的是美麗的環，這些環其實由很多冰塊和小石塊組成。',
    en: {
      name: 'Saturn',
      type: 'Gas giant',
      order: '6th planet from the Sun',
      distance: 'Average distance from the Sun: about 1.434 billion km',
      diameter: 'Diameter: about 120,536 km',
      mass: "Mass: about 95.2 times Earth's mass",
      composition: 'Made mostly of hydrogen and helium, with clear rings of ice and rocky debris',
      rotation: 'Rotation: about 10.7 hours',
      revolution: 'Orbit: about 29.45 Earth years',
      temperature: 'Average cloud-top temperature: about -140°C',
      moons: 'Many known moons; Titan is one of the most important',
      kidFact:
        'Saturn is famous for its beautiful rings, which are made of many pieces of ice and small rocks.',
    },
  },
  {
    id: 'uranus',
    name: '天王星',
    englishName: 'Uranus',
    type: '冰巨行星',
    orbit: 340,
    size: 26,
    orbitDuration: 58,
    rotationDuration: 2.2,
    orbitTilt: 7,
    orbitYaw: 24,
    colorClass: 'uranus',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/uranus-pia18182-16x9-1.jpg?w=1024',
    imageAlt: 'NASA Voyager 2 image of Uranus.',
    imageCredit: 'NASA / JPL-Caltech',
    order: '第 7 顆行星',
    distance: '平均距離太陽約 28.71 億公里',
    diameter: '直徑約 51,118 公里',
    mass: '質量約為地球的 14.5 倍',
    composition: '氫、氦、甲烷，以及水、氨等冰狀物質',
    rotation: '自轉約 17.2 小時，幾乎是躺著轉',
    revolution: '公轉約 84 個地球年',
    temperature: '雲頂平均約 -195°C',
    moons: '已知有多顆衛星',
    kidFact: '天王星的自轉軸傾斜很大，看起來像是側躺著繞太陽轉。',
    en: {
      name: 'Uranus',
      type: 'Ice giant',
      order: '7th planet from the Sun',
      distance: 'Average distance from the Sun: about 2.871 billion km',
      diameter: 'Diameter: about 51,118 km',
      mass: "Mass: about 14.5 times Earth's mass",
      composition: 'Hydrogen, helium, methane, and icy materials such as water and ammonia',
      rotation: 'Rotation: about 17.2 hours, with the planet tilted almost on its side',
      revolution: 'Orbit: about 84 Earth years',
      temperature: 'Average cloud-top temperature: about -195°C',
      moons: 'Multiple known moons',
      kidFact:
        'Uranus has a very tilted rotation axis, so it looks as if it rolls around the Sun on its side.',
    },
  },
  {
    id: 'neptune',
    name: '海王星',
    englishName: 'Neptune',
    type: '冰巨行星',
    orbit: 390,
    size: 25,
    orbitDuration: 70,
    rotationDuration: 2.1,
    orbitTilt: 4,
    orbitYaw: -7,
    colorClass: 'neptune',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/pia01492-neptune-full-disk-16x9-1.jpg?w=1024',
    imageAlt: 'NASA Voyager 2 image of Neptune.',
    imageCredit: 'NASA / JPL-Caltech',
    order: '第 8 顆行星',
    distance: '平均距離太陽約 44.95 億公里',
    diameter: '直徑約 49,528 公里',
    mass: '質量約為地球的 17.1 倍',
    composition: '氫、氦、甲烷，以及冰狀物質',
    rotation: '自轉約 16.1 小時',
    revolution: '公轉約 164.8 個地球年',
    temperature: '雲頂平均約 -200°C',
    moons: '已知有多顆衛星，海衛一很特別',
    kidFact: '海王星有太陽系中非常強的風，風速可以比地球上的颱風快很多。',
    en: {
      name: 'Neptune',
      type: 'Ice giant',
      order: '8th planet from the Sun',
      distance: 'Average distance from the Sun: about 4.495 billion km',
      diameter: 'Diameter: about 49,528 km',
      mass: "Mass: about 17.1 times Earth's mass",
      composition: 'Hydrogen, helium, methane, and icy materials',
      rotation: 'Rotation: about 16.1 hours',
      revolution: 'Orbit: about 164.8 Earth years',
      temperature: 'Average cloud-top temperature: about -200°C',
      moons: 'Multiple known moons; Triton is especially interesting',
      kidFact:
        'Neptune has some of the strongest winds in the solar system, much faster than typhoon winds on Earth.',
    },
  },
  {
    id: 'pluto',
    name: '冥王星',
    englishName: 'Pluto',
    type: '矮行星延伸學習',
    orbit: 438,
    size: 10,
    orbitDuration: 82,
    rotationDuration: 3.2,
    orbitTilt: 17,
    orbitYaw: 34,
    colorClass: 'pluto',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/pluto-new-horizons-pia20291-16x9-1.jpg?w=1024',
    imageAlt: 'NASA New Horizons image of Pluto.',
    imageCredit: 'NASA / Johns Hopkins APL / Southwest Research Institute',
    order: '位於海王星外側的古柏帶天體',
    distance: '平均距離太陽約 59 億公里',
    diameter: '直徑約 2,376 公里',
    mass: '質量約為地球的 0.0022 倍',
    composition: '岩石與冰，表面有氮冰、甲烷冰和一氧化碳冰',
    rotation: '自轉約 6.4 個地球日',
    revolution: '公轉約 248 個地球年',
    temperature: '表面非常寒冷，約 -230°C 左右',
    moons: '5 顆已知衛星，最大的是凱倫',
    kidFact: '冥王星曾經被稱為第九大行星，2006 年後改分類為矮行星。',
    en: {
      name: 'Pluto',
      type: 'Dwarf planet extension',
      order: 'A Kuiper Belt object beyond Neptune',
      distance: 'Average distance from the Sun: about 5.9 billion km',
      diameter: 'Diameter: about 2,376 km',
      mass: "Mass: about 0.0022 times Earth's mass",
      composition: 'Rock and ice, with nitrogen, methane, and carbon monoxide ice on the surface',
      rotation: 'Rotation: about 6.4 Earth days',
      revolution: 'Orbit: about 248 Earth years',
      temperature: 'Extremely cold surface, around -230°C',
      moons: '5 known moons; the largest is Charon',
      kidFact:
        'Pluto was once called the ninth planet, but since 2006 it has been classified as a dwarf planet.',
    },
  },
]

export const sunInfo = {
  name: '太陽',
  englishName: 'Sun',
  type: '恆星',
  imageUrl: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/solar/2023/07/Sun_Features_Solar_Prominence-800x600-1.jpg?crop=faces%2Cfocalpoint&fit=clip&h=600&w=800',
  imageAlt: 'NASA image of the Sun with a solar prominence.',
  imageCredit: 'NASA',
  order: '太陽系中心',
  distance: '位在太陽系中心，行星繞著它公轉',
  diameter: '直徑約 139 萬公里',
  mass: '佔太陽系總質量約 99.8%',
  composition: '主要由氫和氦組成',
  rotation: '不同緯度自轉速度不同，赤道約 25 天',
  revolution: '太陽不是行星，不繞自己當中心公轉',
  temperature: '表面約 5,500°C，核心更高',
  moons: '沒有衛星',
  kidFact: '太陽提供光和熱，是地球生命最重要的能量來源。',
  en: {
    name: 'Sun',
    type: 'Star',
    order: 'Center of the solar system',
    distance: 'Located at the center of the solar system; planets orbit around it',
    diameter: 'Diameter: about 1.39 million km',
    mass: 'Contains about 99.8% of the total mass of the solar system',
    composition: 'Made mostly of hydrogen and helium',
    rotation: 'Rotation speed varies by latitude; the equator takes about 25 days',
    revolution: 'The Sun is not a planet and does not orbit itself as the center',
    temperature: 'Surface temperature: about 5,500°C, with a much hotter core',
    moons: 'No moons',
    kidFact:
      'The Sun provides light and heat, making it the most important energy source for life on Earth.',
  },
}
