export const solarBodies = [
  {
    id: 'mercury',
    name: '水星',
    englishName: 'Mercury',
    type: '岩石行星',
    orbit: 84,
    size: 11,
    orbitDuration: 8,
    rotationDuration: 5,
    orbitTilt: 6,
    orbitYaw: -10,
    colorClass: 'mercury',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/pia15162-mercury-basins-messenger-16x9-1.jpg?w=1024',
    imageAlt: 'NASA MESSENGER spacecraft image of Mercury.',
    imageCredit: 'NASA / Johns Hopkins APL / Carnegie Institution of Washington',
    order: '第 1 顆行星',
    distance: '平均距離太陽約 5,790 萬公里',
    diameter: '直徑約 4,879 公里',
    mass: '質量約為地球的 0.055 倍',
    composition: '岩石、金屬核心，幾乎沒有大氣',
    rotation: '自轉約 58.6 個地球日',
    revolution: '公轉約 88 個地球日',
    temperature: '白天很熱、夜晚很冷，溫差極大',
    moons: '0 顆衛星',
    kidFact: '水星最靠近太陽，但因為幾乎沒有大氣保溫，夜晚會變得非常寒冷。',
  },
  {
    id: 'venus',
    name: '金星',
    englishName: 'Venus',
    type: '岩石行星',
    orbit: 116,
    size: 17,
    orbitDuration: 12,
    rotationDuration: 10,
    orbitTilt: 3,
    orbitYaw: 14,
    colorClass: 'venus',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/venus-mariner-10-pia23791-fig2-16x9-1.jpg?w=1024',
    imageAlt: 'NASA Mariner 10 image of Venus.',
    imageCredit: 'NASA / JPL-Caltech',
    order: '第 2 顆行星',
    distance: '平均距離太陽約 1.082 億公里',
    diameter: '直徑約 12,104 公里',
    mass: '質量約為地球的 0.815 倍',
    composition: '岩石星球，厚重大氣主要是二氧化碳',
    rotation: '自轉約 243 個地球日，方向和多數行星相反',
    revolution: '公轉約 225 個地球日',
    temperature: '表面溫度約 465°C，是最熱的行星',
    moons: '0 顆衛星',
    kidFact: '金星有很厚的雲和溫室效應，所以比離太陽更近的水星還熱。',
  },
  {
    id: 'earth',
    name: '地球',
    englishName: 'Earth',
    type: '岩石行星',
    orbit: 150,
    size: 18,
    orbitDuration: 16,
    rotationDuration: 2.5,
    orbitTilt: 0,
    orbitYaw: 0,
    colorClass: 'earth',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/blue-marble-apollo-17-16x9-1.jpg?w=1024',
    imageAlt: 'Apollo 17 Blue Marble image of Earth.',
    imageCredit: 'NASA',
    order: '第 3 顆行星',
    distance: '平均距離太陽約 1.496 億公里',
    diameter: '直徑約 12,756 公里',
    mass: '質量約 5.97 x 10^24 公斤',
    composition: '岩石、金屬核心、水、氮氣與氧氣大氣',
    rotation: '自轉約 24 小時',
    revolution: '公轉約 365.25 天',
    temperature: '平均表面溫度約 15°C',
    moons: '1 顆衛星：月球',
    kidFact: '地球目前是我們知道唯一有大量液態水和生命的行星。',
  },
  {
    id: 'mars',
    name: '火星',
    englishName: 'Mars',
    type: '岩石行星',
    orbit: 186,
    size: 14,
    orbitDuration: 22,
    rotationDuration: 2.7,
    orbitTilt: 4,
    orbitYaw: -24,
    colorClass: 'mars',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/mars-full-globe-16x9-1.jpg?w=1024',
    imageAlt: 'NASA spacecraft image of Mars as a full globe.',
    imageCredit: 'NASA / JPL-Caltech',
    order: '第 4 顆行星',
    distance: '平均距離太陽約 2.279 億公里',
    diameter: '直徑約 6,792 公里',
    mass: '質量約為地球的 0.107 倍',
    composition: '岩石、鐵氧化物塵土、稀薄二氧化碳大氣',
    rotation: '自轉約 24.6 小時',
    revolution: '公轉約 687 個地球日',
    temperature: '平均約 -65°C',
    moons: '2 顆衛星：火衛一、火衛二',
    kidFact: '火星看起來偏紅，是因為表面有像鐵鏽一樣的物質。',
  },
  {
    id: 'jupiter',
    name: '木星',
    englishName: 'Jupiter',
    type: '氣體巨行星',
    orbit: 234,
    size: 38,
    orbitDuration: 36,
    rotationDuration: 1.6,
    orbitTilt: 1,
    orbitYaw: 8,
    colorClass: 'jupiter',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/jupiter-marble-pia22946-16x9-1.jpg?w=1024',
    imageAlt: 'NASA Juno image of Jupiter.',
    imageCredit: 'NASA / JPL-Caltech / SwRI / MSSS',
    order: '第 5 顆行星',
    distance: '平均距離太陽約 7.785 億公里',
    diameter: '直徑約 142,984 公里',
    mass: '質量約為地球的 317.8 倍',
    composition: '主要由氫和氦組成',
    rotation: '自轉約 9.9 小時',
    revolution: '公轉約 11.86 個地球年',
    temperature: '雲頂平均約 -110°C',
    moons: '已知有許多衛星，包含伽利略四大衛星',
    kidFact: '木星是太陽系最大的行星，上面的「大紅斑」是一個持續很久的大風暴。',
  },
  {
    id: 'saturn',
    name: '土星',
    englishName: 'Saturn',
    type: '氣體巨行星',
    orbit: 288,
    size: 34,
    orbitDuration: 46,
    rotationDuration: 1.8,
    orbitTilt: 2,
    orbitYaw: -18,
    colorClass: 'saturn',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2023/05/pia05380-saturn-with-rings-16x9-1.jpg',
    imageAlt: 'NASA Cassini image of Saturn with its ring system centered in frame.',
    imageCredit: 'NASA / JPL / Space Science Institute',
    hasRing: true,
    order: '第 6 顆行星',
    distance: '平均距離太陽約 14.34 億公里',
    diameter: '直徑約 120,536 公里',
    mass: '質量約為地球的 95.2 倍',
    composition: '主要由氫和氦組成，擁有明顯冰與岩石碎片環',
    rotation: '自轉約 10.7 小時',
    revolution: '公轉約 29.45 個地球年',
    temperature: '雲頂平均約 -140°C',
    moons: '已知有許多衛星，土衛六是其中很重要的一顆',
    kidFact: '土星最有名的是美麗的環，這些環其實由很多冰塊和小石塊組成。',
  },
  {
    id: 'uranus',
    name: '天王星',
    englishName: 'Uranus',
    type: '冰巨行星',
    orbit: 340,
    size: 26,
    orbitDuration: 58,
    rotationDuration: 2.2,
    orbitTilt: 7,
    orbitYaw: 24,
    colorClass: 'uranus',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/uranus-pia18182-16x9-1.jpg?w=1024',
    imageAlt: 'NASA Voyager 2 image of Uranus.',
    imageCredit: 'NASA / JPL-Caltech',
    order: '第 7 顆行星',
    distance: '平均距離太陽約 28.71 億公里',
    diameter: '直徑約 51,118 公里',
    mass: '質量約為地球的 14.5 倍',
    composition: '氫、氦、甲烷，以及水、氨等冰狀物質',
    rotation: '自轉約 17.2 小時，幾乎是躺著轉',
    revolution: '公轉約 84 個地球年',
    temperature: '雲頂平均約 -195°C',
    moons: '已知有多顆衛星',
    kidFact: '天王星的自轉軸傾斜很大，看起來像是側躺著繞太陽轉。',
  },
  {
    id: 'neptune',
    name: '海王星',
    englishName: 'Neptune',
    type: '冰巨行星',
    orbit: 390,
    size: 25,
    orbitDuration: 70,
    rotationDuration: 2.1,
    orbitTilt: 4,
    orbitYaw: -7,
    colorClass: 'neptune',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/pia01492-neptune-full-disk-16x9-1.jpg?w=1024',
    imageAlt: 'NASA Voyager 2 image of Neptune.',
    imageCredit: 'NASA / JPL-Caltech',
    order: '第 8 顆行星',
    distance: '平均距離太陽約 44.95 億公里',
    diameter: '直徑約 49,528 公里',
    mass: '質量約為地球的 17.1 倍',
    composition: '氫、氦、甲烷，以及冰狀物質',
    rotation: '自轉約 16.1 小時',
    revolution: '公轉約 164.8 個地球年',
    temperature: '雲頂平均約 -200°C',
    moons: '已知有多顆衛星，海衛一很特別',
    kidFact: '海王星有太陽系中非常強的風，風速可以比地球上的颱風快很多。',
  },
  {
    id: 'pluto',
    name: '冥王星',
    englishName: 'Pluto',
    type: '矮行星延伸學習',
    orbit: 438,
    size: 10,
    orbitDuration: 82,
    rotationDuration: 3.2,
    orbitTilt: 17,
    orbitYaw: 34,
    colorClass: 'pluto',
    imageUrl: 'https://science.nasa.gov/wp-content/uploads/2024/03/pluto-new-horizons-pia20291-16x9-1.jpg?w=1024',
    imageAlt: 'NASA New Horizons image of Pluto.',
    imageCredit: 'NASA / Johns Hopkins APL / Southwest Research Institute',
    order: '位於海王星外側的古柏帶天體',
    distance: '平均距離太陽約 59 億公里',
    diameter: '直徑約 2,376 公里',
    mass: '質量約為地球的 0.0022 倍',
    composition: '岩石與冰，表面有氮冰、甲烷冰和一氧化碳冰',
    rotation: '自轉約 6.4 個地球日',
    revolution: '公轉約 248 個地球年',
    temperature: '表面非常寒冷，約 -230°C 左右',
    moons: '5 顆已知衛星，最大的是凱倫',
    kidFact: '冥王星曾經被稱為第九大行星，2006 年後改分類為矮行星。',
  },
]

export const sunInfo = {
  name: '太陽',
  englishName: 'Sun',
  type: '恆星',
  imageUrl: 'https://assets.science.nasa.gov/dynamicimage/assets/science/psd/solar/2023/07/Sun_Features_Solar_Prominence-800x600-1.jpg?crop=faces%2Cfocalpoint&fit=clip&h=600&w=800',
  imageAlt: 'NASA image of the Sun with a solar prominence.',
  imageCredit: 'NASA',
  order: '太陽系中心',
  distance: '位在太陽系中心，行星繞著它公轉',
  diameter: '直徑約 139 萬公里',
  mass: '佔太陽系總質量約 99.8%',
  composition: '主要由氫和氦組成',
  rotation: '不同緯度自轉速度不同，赤道約 25 天',
  revolution: '太陽不是行星，不繞自己當中心公轉',
  temperature: '表面約 5,500°C，核心更高',
  moons: '沒有衛星',
  kidFact: '太陽提供光和熱，是地球生命最重要的能量來源。',
}
